POST https://blockverseapi.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "team_name": "mymemm",
    "leader_name": "mypadssword",
    "email": "myemmmadd@akgec.ac.in",
    "hosteler": "yes",
    "year": "1",
    "branch": "CSE",
    "phoneNo": "7234567890",
    "rollNo": "92627890",
    "team_member": {
        "m_name": "utkbdf",
        "m_email": "haramam@akgec.ac.in",
        "m_phoneNo": "929299",
        "m_rollNo": "222222",
        "m_year": "2",
        "m_branch": "cs",
        "m_hosteler": "yes"
    }
}

###
POST http://localhost:9000/register HTTP/1.1
Content-Type: application/json

{
    "team_name": "myuseddddrnamemm",
    "leader_name": "mypadssword",
    "email": "myemmmadilddd@akgec.ac.in",
    "hosteler": "yes",
    "year": "1",
    "branch": "CSE",
    "phoneNo": "7234567890",
    "rollNo": "9234252627890"
}

###
 
POST http://3.6.75.26:5000/register HTTP/1.1
Content-Type: application/json
    
{
    "team_name": "xyz2",
    "l_name":"abc1",
    "l_email":"gracy2112004@akgec.ac.in",
    "l_otp": 569,
    "l_hosteler":true,
    "l_year":2,
    "l_branch":"CS",
    "l_rollNo": 123456780,
    "l_phoneNo":1234567890,
    "m_name":"abc2",
    "m_email":"shashwat2115433@akgec.ac.in",
    "m_otp": 4027,
    "m_hosteler":true,
    "m_year":2,
    "m_branch":"CS",
    "m_rollNo": 123456780342,
    "m_phoneNo":1234567890132
}

###
 
POST http://3.6.75.26:5000/register HTTP/1.1
Content-Type: application/json
    
{
    "team_name": "xyz2",
    "l_name":"abc1",
    "l_email":"utkarsh2110024@akgec.ac.in",
    "l_otp": 59626,
    "l_hosteler":false,
    "l_year":2,
    "l_branch":"CSE",
    "l_rollNo": 123456780,
    "l_phoneNo":1234567890
}

###

POSt http://3.6.75.26:5000/send_email HTTP/1.1
Content-Type: application/json

{
    "email": "utkarsh2110024@akgec.ac.in"
}